### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by gogre** [featurecat/Influencie#2]
Influencie cannot traverse variations, but Lizzie can.  Lizzie produces bestmove colours, which would be interesting to see on top of Influencie's maps.  Mousing over a bestmove could redraw Influencie's shadows, so mousing in and out would enable the viewer to see the change in influence the bestmove would make.  Mousing with shiftkey could show the principal variation, with Influencie's new shadows from the end of that variation, to provide even more insight.

Therefore, please can you hook them up, so Lizzie can draw Influencie's maps, perhaps using a preset discreet natural-looking colour scheme similar to the first of your illustrations, with a slightly reduced Intensity setting so as to not dominate Lizzie's move colours, and..

..with a Stone Influence setting that makes a solitary stone shade its immediate empty neighbours strongly, its neighbours 2 spaces away slightly, and falls short of its neighbours 3 spaces away, so that  a solitary stone on the 3rd line can be seen to influence the edge, but one on the 4th line does not?  

Example attached, which also shows a couple of display adjustments - numbers belonging to white are white, and numbers belonging to black are black, so no need for stone icons on the lhs.  the node graph on the rhs has reduced brightness, contrast and gamma, so it doesn't attract the eye away from what's on the board.
![example](https://user-images.githubusercontent.com/46689669/52181634-ad79c480-283f-11e9-958c-6f6507f2e289.png)

Further request: i believe the bestmove colour is win% and the ring its visit count - visit counts are of interest to bot programmers, but maybe not so much to ordinary players, who mainly want to see what difference a move makes and are less concerned abut how often leela looked at it for her own idiosyncratic reasons.  Exact numbers are again something more of interest to programmers than to players; so an alternative bestmove colour scheme is suggested here: https://www.lifein19x19.com/viewtopic.php?p=240791#p240791

Oh, and you could put the comment subwindow on the left instead of the right, as there is space for it there, because a large graph isn't needed, but a long tree often is when reviewing, so the user can remember where the heck they are in a tree!

**Comment by featurecat** [comment]
I need to find some extra motivation to release Lizzie 0.7 - unfortunately it seems I'm working on it alone for now. But if I did have the time to work on Influencie... I don't think I would merge it with Lizzie. I like the graphic you made, but the problem is that Lizzie is a tool for AI-backed evaluations, and Influencie is just a visually interesting mathematical function - it doesn't actually have a useful analysis ability.

I think Influencie might be a good tool for getting people interested in Go, but I can't see it being paired with Lizzie because it's visualizations aren't up to par with 9d analysis.

I have seen some experiments in AI-based influence heatmaps, though. If those can be sped up so they can be used in real-time (as well as a 9d territory estimator), then that's what I would want to combine with Lizzie.

**Comment by featurecat** [comment]
Oh and about the visit counts... The reason I chose to make the colors follow the visit counts, is because the move Leela Zero actually plays, is the one with the most visits - not the one with the highest winrate. Sometimes even, it leaves the move with the highest winrate with fewer than 100 visits, while it explores other variations by the thousands of visits. But I think it would be a nice option to allow users to set / toggle.

**Comment by gogre** [comment]
i would help if i could speak Java but i can't...
... i will never forget the first end-user test i ever saw - we were a small team producing software that ran stuff that interacted with human operators - one of the senior managers came in and starting pushing buttons at random all over the place!  "Buttons are for pushing!!" he said.  As a still wet-behind-the-ears greenhorn, i thought he was mad and didn't understand computers, but he was right on the money - because our software told military pilots where to fly and when to shoot, and if an operator pushed the wrong button at the wrong time, the consequences could be disasterous.  Our system had to be human operator error foolproof.

as to whether Influencie has any real value, whereas it is, as it stands, just a pretty picture painter, **there is a way to make the picture it paints meaningful**, with only a little jiggery-pokery behind the scenes: https://www.lifein19x19.com/viewtopic.php?p=241243#p241243... 

i'm trying to straighten out and clarify my ideas by defining https://github.com/gogre/irgobot - a potential daughter of Influencie and Lizzie (and maybe Sabaki too) - it's colour-map https://github.com/gogre/irgobot/blob/master/README.md can see and label "obvious" static life and death, but there are plenty of situations, eg involving ko, that are not obvious and can't be worked out without reading.  

So there is an opportunity for Laizy to lend a helping hand:

Entire game whole-board reading does not produce accurate estimates of local current life-and-death status, because the life and death status of a local situation can change dramatically, when eg Laizy later decides it is strategically sensible to tenuki and sacrifice something that could have lived - in furikawari exchanges or ko fights going on somewhere else and suchlike.  

But there is potential for whole-board Monte-Carlo simulations to be used:  For example, if Laizy - or one of the tsumego algorithms - could be let loose on a carefully circumscribed local area, it could compute dynamic local life and death.

And here's where Influencie could play another role, 

because although my revision of djhbrown's  colour-map algorithm is able to circumscribe a colour-controlled area, that area is too confined for proper local life and death analysis - 

but Influencie's shadow map, based upon a colour map, might indeed be sufficient 

laizy's local minigame will be much quicker than a regular whole-board analysis of a single move, which Lizzie can already do faster than i can blink,

Once Influencie has circumscribed the area irgobot wants Laizy to investigate, irgobot first fills up the entire rest of the board with minimally living groups.

Even then, laizy, playing both sides, will occasionally want to fill in her own eyes, so irgotbot has to choose each move for her after laizy has made her value judgements.

irgobot does this by simply selecting laizy's best move which is in the area of focus, and then asking laizy to find the best move for the other side, and so on, 

irgobot will refuse to remove the penultimate liberty of any group within the area of focus, and pass instead, so laizy won't be allowed to kill herself,

laizy is such a silly girl, she needs irgobot to hold her hand for her,

Then, by the end of the minigame, laizy will have captured all the dead stones,

Then, by comparing the end of that minigame board with the current position, irgobot can see which stones in the local area of interest are going to die, and mark them accordingly.

Now irgobot draws a new colour map, as if those dead stones were not there,

this then becomes the basis for drawing a meaningful Influencie shadow map, and - voila! - you have something really worthwhile,

an example of irgotbot in action will be illustrated in an upcoming new video in the series "influence concensus maps"
https://www.youtube.com/watch?v=zemcZKzgE7w&list=PLfW0QbIZVHrf3fKo5Yp6soqOzgm6j3Jrc&index=1
i will let you know here when the new one is uploaded.  it will compare Michael Redmond's analysis of a position in game 9 of Zero vs Master with what irgobot makes of it, focussing on estimating territory in the early part of the midgame.

___________________________________________________

On the subject of visit counts, as a weak player,  i am happy to consider any advice Laizy can give! :)

But i would like to know what difference a day makes, so i would like visual feedback on how my win rate changes (changed) from one move to the next, at the time it is happening (at the time i am reviewing), right there in front of my eyes, where i am looking, on the board.  Imagine what it would be like to drive a car if you could only see what's changing in front of you by having to consult a graph being drawn by your backseat driver...

So i came up with a 2-ring colour scheme, where the thin outer ring indicates delta(win%), the thick inner ring indicates win% and the bullseye indicates whose move it is (black or white).  Since writing https://www.lifein19x19.com/viewtopic.php?p=240791#p240791, i am thinking that my suggested colour scheme can be improved upon, namely something like:
green = safe(ish) = 48-55% winrate;  -0.5 - 2% delta
yellow = shining = 56+%winrate;  >2% delta
brown = not so good = 40-47%winrate;  -2 to -0.6% delta
red = danger = <40% winrate;  < -2% delta

so, eg, a brown inner ring with a green outer ring means you are not safe yet but may have a chance of getting back to even; and anything with a red outer ring is a clear blunder

and a red inner ring with a red outer ring means you need to buy Ishida's book! :)
